pipeline:
  name: CI
  identifier: CI
  projectIdentifier: datarobotopentelemetry
  orgIdentifier: MMM
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: datarobot-opentelemetry
        build: <+input>
  stages:
    - stage:
        name: Git Hash
        identifier: Git_Hash
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Git Hash
                  identifier: Git_Hash
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: alpine/git
                    shell: Sh
                    command: export GIT_HASH_SHORT=$(git rev-parse --short HEAD)
                    outputVariables:
                      - name: GIT_HASH_SHORT
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cigeneral
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
    - stage:
        name: Build Docker Image CI
        identifier: Build_Docker_Image
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Image
                  identifier: Build_and_Push_Image
                  spec:
                    connectorRef: org.mmmdockerhubwriteorg
                    repo: datarobotdev/datarobot-opentelemetry
                    tags:
                      - ci-python-<+pipeline.stages.Git_Hash.spec.execution.steps.Git_Hash.output.outputVariables.GIT_HASH_SHORT>
                    dockerfile: ci-python.Dockerfile
                    optimize: true
                    remoteCacheRepo: datarobotdev/datarobot-opentelemetry
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: "1"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cigeneral
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              containerSecurityContext:
                privileged: false
              os: Linux
          caching:
            enabled: false
            paths: []
          slsa_provenance:
            enabled: false
    - parallel:
        - stage:
            name: Linting
            identifier: Linting
            type: CI
            spec:
              cloneCodebase: true
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: account.cigeneral
                  namespace: harness-delegate-ng
                  automountServiceAccountToken: true
                  nodeSelector: {}
                  os: Linux
              execution:
                steps:
                  - parallel:
                      - step:
                          type: Run
                          name: Ruff Linting
                          identifier: Ruff_Linting
                          spec:
                            connectorRef: account.dockerhub_datarobot_read
                            image: datarobotdev/datarobot-opentelemetry:ci-python-<+pipeline.stages.Git_Hash.spec.execution.steps.Git_Hash.output.outputVariables.GIT_HASH_SHORT>
                            shell: Sh
                            command: |-
                              echo "Run Ruff Linting"
                              cd python/datarobot-opentelemetry
                              uv run --no-sync ruff check src
                      - step:
                          type: Run
                          name: Ruff Formatting
                          identifier: Black_Linting
                          spec:
                            connectorRef: account.dockerhub_datarobot_read
                            image: datarobotdev/datarobot-opentelemetry:ci-python-<+pipeline.stages.Git_Hash.spec.execution.steps.Git_Hash.output.outputVariables.GIT_HASH_SHORT>
                            shell: Sh
                            command: |-
                              echo "Run Ruff Formatting"
                              cd python/datarobot-opentelemetry
                              uv run --no-sync ruff format --check src
                      - step:
                          type: Run
                          name: Run Mypy
                          identifier: Run_Mypy
                          spec:
                            connectorRef: account.dockerhub_datarobot_read
                            image: datarobotdev/datarobot-opentelemetry:ci-python-<+pipeline.stages.Git_Hash.spec.execution.steps.Git_Hash.output.outputVariables.GIT_HASH_SHORT>
                            shell: Sh
                            command: |-
                              echo "Run Mypy"
                              cd python/datarobot-opentelemetry
                              uv run --no-sync mypy --pretty --strict src
              caching:
                enabled: false
                paths: []
        - stage:
            name: Unit Test
            identifier: Unit_Test
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run Unit Test
                      identifier: Run_Unit_Test
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: datarobotdev/datarobot-opentelemetry:ci-python-<+pipeline.stages.Git_Hash.spec.execution.steps.Git_Hash.output.outputVariables.GIT_HASH_SHORT>
                        shell: Sh
                        command: |-
                          echo "Run Unit Test"
                          cd python/datarobot-opentelemetry
                          uv run --no-sync pytest -svvv tests/unit --junitxml=/harness/test_results/unit-test-results.xml
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - /harness/test_results/unit-test-results.xml
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: account.cigeneral
                  namespace: harness-delegate-ng
                  automountServiceAccountToken: true
                  nodeSelector: {}
                  os: Linux
              caching:
                enabled: false
                paths: []
        - stage:
            name: Source Code License Check
            identifier: License_Check
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: License Check
                      identifier: License_Check
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: ghcr.io/apache/skywalking-eyes/license-eye
                        shell: Sh
                        command: |-
                          echo "Run License Check"
                          license-eye -v info -c .licenserc.yaml header check
              infrastructure:
                useFromStage: Build_Docker_Image
              caching:
                enabled: false
                paths: []
              slsa_provenance:
                enabled: false
    - stage:
        name: Integration Test
        identifier: Integration_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cigeneral
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - parallel:
                  - step:
                      type: Background
                      name: Start Elasticsearch
                      identifier: Start_Elasticsearch
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: datarobotdev/mirror_chainguard_datarobot.com_elasticsearch-iamguarded:9.2-drbuild-1048
                        shell: Sh
                        envVariables:
                          TINI_SUBREAPER: "true"
                          discovery.type: single-node
                          xpack.security.enabled: "false"
                          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
                          cluster.name: datarobot-opentelemetry-es-ci
                          path.repo: /tmp/elasticsearch_backups
                        resources:
                          limits:
                            memory: 1Gi
                  - step:
                      type: Background
                      name: Start DrAuth Mock Server
                      identifier: Start_DrAuth_Mock_Server
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: datarobotdev/datarobot-opentelemetry:ci-python-<+pipeline.stages.Git_Hash.spec.execution.steps.Git_Hash.output.outputVariables.GIT_HASH_SHORT>
                        shell: Sh
                        command: python3 python/datarobot-opentelemetry/tests/mock_auth_server.py
              - step:
                  type: Run
                  name: Wait for Elasticsearch
                  identifier: Wait_for_Elasticsearch
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: alpine/curl
                    shell: Sh
                    command: |-
                      counter=0
                      while [[ $counter -lt 30 ]]; do
                          if curl http://localhost:9200; then
                              break
                          else
                              echo "Waiting for Elasticsearch to start..."
                              counter=$((counter+1))
                              sleep 10
                          fi
                      done

                      if [[ $counter -eq 30 ]]; then
                          echo "Error: Elasticsearch not available after 300 seconds"
                          exit 1
                      fi
              - step:
                  type: Run
                  name: Wait for DrAuth Mock Server
                  identifier: Wait_for_DrAuth_Mock_Server
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: alpine/curl
                    shell: Sh
                    command: |-
                      counter=0
                      while [[ $counter -lt 30 ]]; do
                          if curl http://localhost:8880; then
                              break
                          else
                              echo "Waiting for DrAuth Mock Server to start..."
                              counter=$((counter+1))
                              sleep 5
                          fi
                      done

                      if [[ $counter -eq 30 ]]; then
                          echo "Error: DrAuth Mock Server not available after 150 seconds"
                          exit 1
                      fi
              - step:
                  type: Run
                  name: Run Datavolt Migrations
                  identifier: Run_Datavolt_Migrations
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: datarobotdev/datavolt:latest
                    shell: Sh
                    envVariables:
                      DATAVOLT_ELASTIC_SEARCH_LB_URL: http://localhost:9200
                    command: |-
                      esmigrate upgrade head -c /opt/migrations/esmigrate.ini
                      export MIGRATIONS_EXIT_CODE=$?
                      if [ $MIGRATIONS_EXIT_CODE -ne 0 ]; then
                        echo "Datavolt migrations failed with exit code: $MIGRATIONS_EXIT_CODE"
                        exit $MIGRATIONS_EXIT_CODE
                      fi
              - parallel:
                  - step:
                      type: Background
                      name: Run Datavolt
                      identifier: Run_Datavolt
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: datarobotdev/datavolt:latest
                        shell: Sh
                        envVariables:
                          DATAVOLT_ELASTIC_SEARCH_URL: http://localhost:9200
                        command: python3.12 -m datavolt.web
                  - step:
                      type: Run
                      name: Wait for Datavolt
                      identifier: Wait_for_Datavolt
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: alpine/curl
                        shell: Sh
                        command: |-
                          counter=0
                          while [[ $counter -lt 30 ]]; do
                              if curl http://localhost:7000/health; then
                                  break
                              else
                                  echo "Waiting for Datavolt to start..."
                                  counter=$((counter+1))
                                  sleep 10
                              fi
                          done
                          if [[ $counter -eq 30 ]]; then
                              echo "Error: Datavolt is not available after 300 seconds"
                              exit 1
                          fi
              - step:
                  type: Background
                  name: Start datarobot-otel-collector
                  identifier: Start_datarobototelcollector
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: datarobotdev/datarobot-otel-collector:latest
                    shell: Sh
                    command: /app/start_collector.sh
                    envVariables:
                      ELASTICSEARCH_URL: http://localhost:9200
                      ELASTICSEARCH_USERNAME: elastic
                      ELASTICSEARCH_PASSWORD: doesntmatter
                      DR_AUTH_SERVER_URL: http://localhost:8880/
                      DR_AUTH_TOKEN_ENDPOINT_URI: http://localhost:8880/token
                      DR_AUTH_RETRIES_COUNT: "5"
                      OTEL_BATCH_TIMEOUT: 1s
                      OTEL_FAST_BATCH_TIMEOUT: 0s
                      DR_AUTH_CLIENT_ID: clientID
                      DR_AUTH_CLIENT_SECRET: Secret
                      DR_AUTH_VERIFY_PERMISSIONS: "true"
                      DR_AUTH_FEATURE_FLAGS: ENABLE_MLOPS,ENABLE_GENAI_EXPERIMENTATION
                      DR_AUTH_ENTITY_HEADER: X-DataRobot-Entity-Id
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: "2"
              - step:
                  type: Run
                  name: Wait for OpenTelemetry Collector
                  identifier: Wait_for_OpenTelemetry_Collector
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: alpine/curl
                    shell: Sh
                    command: |-
                      counter=0
                      while [[ $counter -lt 30 ]]; do
                          if curl http://localhost:13133; then
                              break
                          else
                              echo "Waiting for OpenTelemetry Collector to start..."
                              counter=$((counter+1))
                              sleep 5
                          fi
                      done
                      if [[ $counter -eq 30 ]]; then
                          echo "Error: OpenTelemetry Collector is not available after 150 seconds"
                          exit 1
                      fi
              - step:
                  type: Run
                  name: Run Integration Tests
                  identifier: Run_Integration_Tests
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: datarobotdev/datarobot-opentelemetry:ci-python-<+pipeline.stages.Git_Hash.spec.execution.steps.Git_Hash.output.outputVariables.GIT_HASH_SHORT>
                    shell: Sh
                    command: |-
                      echo "Running integration tests"
                      cd python/datarobot-opentelemetry
                      uv run --no-sync pytest -svvv tests/integration --junitxml=/harness/test_results/integration-test-results.xml
                    envVariables:
                      DR_OTEL_ENDPOINT: http://localhost:4318
                      DR_ENTITY_TYPE: deployment
                      DR_ENTITY_ID: 68af4e4dab41f0ebc9badb49
                      DR_API_BASE_URL: http://localhost:7000
                      DR_ORG_ID: 57eb3347d75f1670ebc5c4bd
                      DATAROBOT_API_TOKEN: datavolt
                      DATAVOLT_URL: http://localhost:7000
                      DATAVOLT_USER: datavolt
                      DATAVOLT_PASSWORD: datavolt
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - /harness/test_results/integration-test-results.xml
            description: ""