[project]
name = "datarobot-opentelemetry"
version = "0.1.0"
description = "OpenTelemetry utilities and encapsulation of semantic naming conventions for improved integration with DataRobot."
readme = "README.md"
authors = [
    { name = "DataRobot", email = "taras.nek@datarobot.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
